src/App.vue, src/assets/styles/elementUi.scss, src/base/line/lin-1px.vue, src/components/layout/AppMain.vue, src/config/index.js
=> feat:修改导航条宽度、line组件线条颜色

src/components/layout/MenuTab.vue, src/views/login/Login.vue, vue.config.js
修复因为 justify-content: space-evenly属性在ie、edge浏览器下兼容性问题。
=> 修复MenuTab显示问题

public/index.html, src/components/base/button/lin-button-group.vue, src/components/base/button/lin-button.vue, src/components/base/icon/lin-icon.vue, src/components/base/table/lin-table.vue, src/main.js
* fix: some eslint
* fix: 修复日志页面默认请求用户权限问题
* chore: 调整目录结构
* token: 退出移除token
* fix: 修复一些bug
* optimize: view logic
* 在线引入iconfont
* 优化xlsx打包速度
=> Optimize (#82):优化xlsx打包速度

script/plugin-get-config.js, src/components/layout/MenuTab.vue, src/config/index.js, src/store/getters.js, src/store/state.js
=> 添加兼容Tab模式下未配置path导致的无法打开页面问题

src/assets/styles/realize/element-variables.scss, src/plugins/LinCmsUi/stage-config.js, src/plugins/LinCmsUi/views/tag/Tag.vue
=> feat(linCmsUi): 增加linCmsUi tag 样式组件

.prettierrc.js
=> style:  增加.prettier.js配置文件

src/lin/models/admin.js
=> 修复更新用户密码api请求路径错误

.env.development, .env.production, package.json, src/component/base/table/lin-table.vue, src/component/layout/side-bar.vue, src/config/error-code.js, src/lin/plugin/axios.js
=> refactor: 优化路由及分页

src/view/admin/group/group-edit.vue, src/view/admin/group/group-permission.vue
=> fix(permission): handle multiple modification permissions

src/model/book.js, src/view/book/book-list.vue
=> fix(model): fix typo

.eslintrc.js
=> fix(eslint): babel eslint sometimes appear range error

src/view/login/login.vue
=> fix(config): defualt routing according to configuration item

src/plugin/custom/view/gallery.vue, src/plugin/lin-cms-ui/view/basic/icon/icon.vue, src/plugin/lin-cms-ui/view/table/table-combo.vue
=> fix(souce-code): 修改 souce-code 失效链接

package-lock.json, src/component/base/table/lin-table.vue.rej, src/component/layout/user.vue, src/lin/plugin/preview/index.js, src/main.js, src/view/about/about.vue, src/view/center/center.vue, src/view/login/login.vue, vue.config.js
=> feat(login): 375 [Migration] Complete login logic

src/view/admin/group/group-list.vue, src/view/admin/user/user-list.vue
=> Admin; 如果请求异常导致的 Cannot read property 异常

src/lin/model/admin.js
=> fix(model): fix variable spelling error

src/lin/filter/index.js, src/main.js, src/view/log/log.vue
=> feat: update global filters

src/lin/model/admin.js, src/lin/model/user.js, src/view/admin/group/group-list.vue, src/view/admin/user/use-user.js, src/view/admin/user/user-create.vue, src/view/admin/user/user-info.vue, src/view/admin/user/user-list.vue, src/view/admin/user/user-password.vue, src/view/book/book.vue
=> User management

package-lock.json, package.json
=> fix(*): Vue.js is not detected with Vue3

package-lock.json, package.json, src/component/layout/menu-tab.vue, src/config/stage/admin.js, src/view/admin/group/group-create.vue, src/view/admin/group/group-edit.vue, src/view/admin/group/group-list.vue, src/view/admin/group/group-permission.vue, src/view/admin/group/use-group.js
=> refactor(group): Migration to Vue3

src/lin/plugin/axios.js
=> fix axios: 正确显示请求的message信息

src/store/action.js
=> fix(logout): clear all storage when logging out

package-lock.json, package.json, src/component/layout/sidebar/search.vue, src/component/layout/sidebar/sidebar.vue
=> feat(sidebar): pull out search component

.npmrc, package-lock.json, package.json, src/lin/util/exportExcel.js, src/lin/util/parseTime.js, src/view/book/book-list.vue, vue.config.js
+ 将node-sass版本改为了 4.13.1
+ 添加了 npmrc文件将node-sass的资源地址改为了 淘宝镜像源的地址,解决安装经常报错的问题
+ vue.config.js文件添加了开发模式下的代理
=> 添加 开发模式下代理,修改node-sass版本以及添加 npmrc文件解决 安装node-sass报错问题

package-lock.json, package.json, src/component/base/tinymce/import-all.js, src/component/base/tinymce/index.vue, src/plugin/custom/view/tinymce.vue
=> feat(tinymce): migrate tinymce to @tinymce/tinymce-vue to adapt to Vue3
